travis:
  secure:
    BINSTAR_TOKEN: ttrbys2XuLqRIu6BU8M1z7jmtb6a0xg5KDQpacyXsSriJfl2BbQDVbn066fy65wa1nFjnfKeRC1Ti836wBskrimjBA215mtYjL1W4GCHa/TS6iSRF9ZAI67KHyJ7Nu8qvAR5TpkurzVG5i9GdDHb1tB8cJNI6vy+aJhbGaVmpXilWc1TGasKjMHX2Uj+k6LC7zxGmYswDpjxh0XxnxHvcavOLDFEOnGCRjY0UbeCtof23IvZJYczOUPpe6FFMY4vyJ4hjJIc6FSJcjkcleFaGUaR08OzPmpBHrcB54OegghVKK8gyO31fdlBdA2qCa0pszggXPlm11tHwEU/1uPUjZ3/tM4O0teEtAHTTwvetSXel/TTG+QA/F0T2U/z6YEQKKuAjyYi7OuxPEaHxXg+yy2deHKVOva97vlD11x9PPdZJJ1iJNDSn9pD69rvZDYTo5jjD9KYQwTYkdu4PcreUT2LFI1Jpl2hnXUirU05kXDL6RlIK0+HG2nw0fscvhnbierotwhIFfY07Oa1mnvjVJLGDJmD34YIlW9mfvU3srqZmIyZyrk4rgVc24qdh6Rt9O/bsBfTc9MLUj2tdu+0ZJu2LjSt1RfskVYvKd9TNillmjc2bkCo8LzJO02lf+QlWEt1LtcSL3b/ulmF5CXAVpqvo0QwNX3u/XO/Lv4UN+g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
