travis:
  secure:
    BINSTAR_TOKEN: STdO3ogfLhMVWnEJaLDiIZdGEoUGBLoHWkpdeLx293tBiHciO7uqR7XkD2tC5aWS9jfQs4xXu8dDvvtrHXid4+QSFzsF02A7c5rp354WWE7Fd9aTJv31ag47OoBpMMeqEu6ZYGPiC8KFmGvXZeuhZ0zM9HyxSmS/y8C4Jw/0ZZYDWV81kCgqrEIuNbm/v6eizBd1q3dW6W0zAG7rJOXl4vXCIPaS1oCduImvkeoKS6UOrQQu1x1jHvME2GeRRgcOQSzGF28w4IJUY2p+SmM/+j4Mip/qiBGFyfHfgCbEmI8+ANs+Dx9bJXX0TZya8Lfm2oyLByq+OuIS6i/GSEkHxVg7yZuwf/AHhGYqQAIalMcOUbTnSaM2ScxJWMm0nDIyllaD3YlBe/VOtnRaSx4yJZayrWIpXLLkfUWxJWKYmnMdckVOACvWbVTkFjQUjgvdrj/qh9LnwAELFxgZAgtffoV5uqvdr/1EALjD/Tj9dRUaGTMIG2+/jbLNJLkMIKsh6Rh9afMGiEXd1LJw/vUVCyTwvXNuo2SYWYNEgdyJw++DyPu7GUry+oG8kP0YQr6C6CW1HayC3F8d7sK+kCA2RtxKhTqrSFdWvIU3ZWH5gEVFCmx24xXRjw/Kp/kONx3G3EQjXgTyuI/iFeDFmHmj+z4Vmt3PjeRq4RhOTmlQ+rA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
